### ISSUE TITLE
Install MySQL v8.0.3 and MySQL WorkBench

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Multiple-days-Non-Profits-and-Health-Wellness-Group-B#16]
**Acceptance Criteria:**

- [ ] Install myql v 8.0.3 from - `https://dev.mysql.com/downloads/installer/`
- [ ] install MySQL workbench from - `https://dev.mysql.com/downloads/workbench/`

**Validation Criteria:**

- [ ] Run MySQL --version in cmd.
- [ ] Run workbench ide to make sure it works properly.

**Comment by mayxxluu** [comment]
When we set up MySQL Server v8.0.30, which server configuration type should we choose? 
![image](https://user-images.githubusercontent.com/77411867/192949749-88f0d5ce-da50-4448-88ad-e7e0b0604209.png)

**Comment by Harman-Sahota** [comment]
I did not have that when i downloaded SQL but I think most appropriate would be to use the developer computer since I saw this on their site "A computer that hosts many other applications, and typically this is your personal workstation. This setting configures MySQL to use the least amount of memory." , plus your computer is gonna be your own workspace and not a server so that should be what you choose.

**Comment by mayxxluu** [comment]
Good to know, thanks Harman!

**Comment by Harman-Sahota** [comment]
> Good to know, thanks Harman!

no worries!

**Comment by AbdulazizAlmutlaq0** [comment]
Every team member have successfully installed MySQL and MySQL WorkBench
