### ISSUE TITLE
Setup python on your computer if you don't have it 

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Multiple-days-Non-Profits-and-Health-Wellness-Group-B#19]
**Acceptance Criteria:**

- [ ] download python from - (https://www.python.org/downloads/)
- [ ] This must be done by Thursday, Sept 29 10 am

**Validation Criteria:**

- [ ] run "python --version" on your computer/laptop on your cmd/terminal

**Comment by mayxxluu** [comment]
I have talked with all team members and everyone has said they installed Python on their machine.
