### ISSUE TITLE
Upload the documentation of the team meeting - sept 28

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Multiple-days-Non-Profits-and-Health-Wellness-Group-B#21]
**Acceptance Criteria:**

- [ ] The team agreement documentation is changed as per needs.
- [ ] Everything discussed in the meeting is documented.

**Comment by mayxxluu** [comment]
Updated the title to Sept. 28 as the meeting was postponed

**Comment by Harman-Sahota** [comment]
Thank you for correcting this Maysey!
